use crate::{
    cheribuild_config::CheribuildPaths,
    command::{install_bin, install_bins_from},
    config::{self, Config},
    context::Context,
    status,
};
use anyhow::{bail, Context as _, Result};
use owo_colors::OwoColorize;
use std::{fs, path::Path, process::Command};

pub(crate) fn run(ctx: &mut Context) -> Result<()> {
    let config = Config::load_and_print(&config::path()?)?;
    let rust_dir = config.rust_dir();

    if !rust_dir.join("x.py").exists() {
        bail! {
            "{} does not look like a rust checkout. Run {} first",
            rust_dir.display(),
            "crability fetch".bold()
        }
    }

    // Write the config.toml
    let paths = CheribuildPaths::read()?;
    let config_toml = rust_dir.join("config.toml");
    status!("Writing {}", config_toml.display().underline());
    fs::write(&config_toml, generate_config_toml(&config, &paths))
        .with_context(|| format!("writing {}", config_toml.display()))?;

    // Write the cheri-config.sh script
    let cheri_home = paths.source_root.to_str().context("non-UTF-8 path")?;
    let cheri_config = config.rust_dir().join("cheri-config.sh");
    status!("Writing {}", cheri_config.display().underline());
    fs::write(&cheri_config, generate_cheri_config(cheri_home))
        .with_context(|| format!("writing {}", cheri_config.display()))?;

    ctx.run(
        Command::new("python3")
            .current_dir(&rust_dir)
            .args(["x.py", "build"]),
    )?;

    // Install the binaries in ~/.crability/bin
    install_binaries(&config, &rust_dir)?;

    Ok(())
}

pub fn install_binaries(config: &Config, rust_dir: &Path) -> Result<()> {
    // FIXME: This is the only host target supported for now :(
    const HOST_TARGET: &str = "x86_64-unknown-linux-gnu";

    let stage1_bin_dir = rust_dir
        .join("build")
        .join(HOST_TARGET)
        .join("stage1")
        .join("bin");

    let bin_dir = config.bin_dir();
    status!(
        "Installing the binaries inside {}",
        bin_dir.display().underline()
    );
    install_bins_from(&stage1_bin_dir, &bin_dir)?;

    // Newer host cargos pass flags like --check-cfg that the pinned rustc rejects, so a matching
    // cargo has to ship with the toolchain. x.py only puts one in stage1 when tools/cargo is
    // built; otherwise fall back to the stage0 cargo, like the fork's own wrapper scripts do.
    let stage0_cargo = rust_dir
        .join("build")
        .join(HOST_TARGET)
        .join("stage0")
        .join("bin")
        .join("cargo");
    if fs::symlink_metadata(bin_dir.join("cargo")).is_err() && stage0_cargo.exists() {
        install_bin(&stage0_cargo, &bin_dir)?;
    }

    Ok(())
}

/// Overwrite cheri-config.sh with the script pointed at CHERI_HOME
fn generate_cheri_config(cheri_home: &str) -> String {
    format!(
        r#"#!/bin/bash

# Set your cheri build directory here
CHERI_HOME="{cheri_home}"
"#
    )
}

/// The config.toml adjusted from the `config.toml.sarah` example to include the
/// bare-metal target.
fn generate_config_toml(config: &Config, paths: &CheribuildPaths) -> String {
    let sdk = paths.morello_sdk_bin();
    let sdk = sdk.display();
    let rust = config.rust_dir();
    let rust = rust.display();

    format!(
        r#"# Generated by crability, do not edit by hand. Paths come from
# ~/.config/cheribuild.json and ~/.config/crability/config.json;
# edit those and re-run `crability rust` instead.

# Includes one of the default files in src/bootstrap/defaults
profile = "codegen"
changelog-seen = 2

[rust]
incremental = true
deny-warnings = false

[build]
target = ["x86_64-unknown-linux-gnu", "aarch64-unknown-none-purecap"]

# Host target: link the compiler against the Morello build of LLVM. The
# Morello fork supports all the normal architectures plus the Morello-specific
# options we need for cross-compiling.
[target.x86_64-unknown-linux-gnu]
llvm-config = "{sdk}/llvm-config"

[target.aarch64-unknown-none-purecap]
llvm-config = "{sdk}/llvm-config"
cc = "{rust}/clang-morello.sh"
cxx = "{rust}/clang++-morello.sh"
linker = "{rust}/clang-morello.sh"
# Use the Morello SDK's binutils for consistency; leaving these out entirely
# confuses the build system.
ar = "{sdk}/ar"
ranlib = "{sdk}/ranlib"

[target.aarch64-unknown-freebsd]
# The wrappers force clang to use the right target and system libraries;
# without them the build defaults to host libc/libm, which is the wrong arch.
cc = "{rust}/clang-freebsd.sh"
cxx = "{rust}/clang++-freebsd.sh"
linker = "{rust}/clang-freebsd.sh"
ar = "{sdk}/ar"
ranlib = "{sdk}/ranlib"

[target.aarch64-unknown-freebsd-purecap]
cc = "{rust}/clang-morello.sh"
cxx = "{rust}/clang++-morello.sh"
linker = "{rust}/clang-morello.sh"
ar = "{sdk}/ar"
ranlib = "{sdk}/ranlib"

# Compile programs with e.g.:
# build/x86_64-unknown-linux-gnu/stage1/bin/rustc --out-dir /tmp/build \
#   --target aarch64-unknown-freebsd -C linker={rust}/clang-freebsd.sh test.rs
"#
    )
}
